"""
=============================================================
STEP 2: Embedding & Vector Store
=============================================================
This module handles:
- Loading chunks from Step 1
- Generating embeddings using Sentence Transformers
- Storing embeddings in ChromaDB (persistent) and FAISS
- Building the searchable vector index

Run this file standalone to build the vector store:
    python step2_embed.py
=============================================================
"""

import json
import numpy as np
from pathlib import Path
from typing import List, Dict, Optional
from sentence_transformers import SentenceTransformer

# ── We provide TWO vector store options: ChromaDB and FAISS ──
# Uncomment whichever you prefer

# Option A: ChromaDB (recommended - persistent, easy to use)
import chromadb
from chromadb.config import Settings

# Option B: FAISS (faster for large datasets)
# import faiss


# ── Configuration ──────────────────────────────────────────
CHUNKS_PATH = "data/chunks.json"
EMBEDDING_MODEL = "all-mpnet-base-v2"   # Good balance of speed & quality
# Alternative: "all-MiniLM-L6-v2"       # Faster, slightly less accurate
CHROMA_PERSIST_DIR = "data/chroma_db"
FAISS_INDEX_PATH = "data/faiss_index"
COLLECTION_NAME = "jaysynth_docs"


# ── 2A: Load Chunks ───────────────────────────────────────
def load_chunks(chunks_path: str = CHUNKS_PATH) -> List[Dict]:
    """Load chunks generated by Step 1."""
    with open(chunks_path, 'r', encoding='utf-8') as f:
        chunks = json.load(f)
    print(f"✅ Loaded {len(chunks)} chunks from {chunks_path}")
    return chunks


# ── 2B: Initialize Embedding Model ────────────────────────
def load_embedding_model(model_name: str = EMBEDDING_MODEL) -> SentenceTransformer:
    """
    Load Sentence Transformer model for generating embeddings.
    
    Model choices explained:
    - all-mpnet-base-v2: Best quality, 768 dimensions, slightly slower
    - all-MiniLM-L6-v2:  Good quality, 384 dimensions, very fast
    - multi-qa-mpnet-base-dot-v1: Optimized for Q&A retrieval
    """
    print(f"📦 Loading embedding model: {model_name}")
    model = SentenceTransformer(model_name)
    print(f"✅ Model loaded. Embedding dimension: {model.get_sentence_embedding_dimension()}")
    return model


# ── 2C: Generate Embeddings ───────────────────────────────
def generate_embeddings(
    chunks: List[Dict],
    model: SentenceTransformer
) -> np.ndarray:
    """
    Generate embeddings for all chunks.
    
    For better retrieval in a sales context, we prepend
    metadata to each chunk text before embedding.
    """
    # Prepare texts with context prefix for better retrieval
    texts = []
    for chunk in chunks:
        # Adding section context improves retrieval accuracy
        section = chunk["metadata"].get("section_title", "")
        text = f"Section: {section}\n{chunk['text']}"
        texts.append(text)
    
    print(f"🔄 Generating embeddings for {len(texts)} chunks...")
    embeddings = model.encode(
        texts,
        show_progress_bar=True,
        batch_size=32,
        normalize_embeddings=True  # Normalize for cosine similarity
    )
    
    print(f"✅ Embeddings generated. Shape: {embeddings.shape}")
    return embeddings


# ── 2D: Store in ChromaDB (Option A - Recommended) ────────
def build_chroma_store(
    chunks: List[Dict],
    embeddings: np.ndarray,
    persist_dir: str = CHROMA_PERSIST_DIR,
    collection_name: str = COLLECTION_NAME
):
    """
    Build a ChromaDB vector store.
    ChromaDB is recommended because:
    - Persistent storage (survives restarts)
    - Built-in metadata filtering
    - Easy to update/delete documents
    """
    Path(persist_dir).mkdir(parents=True, exist_ok=True)
    
    # Initialize ChromaDB client with persistence
    client = chromadb.PersistentClient(path=persist_dir)
    
    # Delete existing collection if rebuilding
    try:
        client.delete_collection(collection_name)
    except Exception:
        pass
    
    # Create collection
    collection = client.create_collection(
        name=collection_name,
        metadata={"description": "Jaysynth Orgochem product documentation"}
    )
    
    # Prepare data for insertion
    ids = [str(chunk["chunk_id"]) for chunk in chunks]
    documents = [chunk["text"] for chunk in chunks]
    metadatas = [chunk["metadata"] for chunk in chunks]
    
    # Add to collection
    collection.add(
        ids=ids,
        documents=documents,
        embeddings=embeddings.tolist(),
        metadatas=metadatas
    )
    
    print(f"✅ ChromaDB collection '{collection_name}' built with {collection.count()} documents")
    print(f"   Persisted to: {persist_dir}")
    return client, collection


# ── 2E: Store in FAISS (Option B - For large scale) ───────
def build_faiss_store(
    chunks: List[Dict],
    embeddings: np.ndarray,
    index_path: str = FAISS_INDEX_PATH
):
    """
    Build a FAISS vector index.
    FAISS is recommended when:
    - You have very large datasets (100K+ chunks)
    - You need maximum search speed
    - You're comfortable managing metadata separately
    """
    import faiss
    
    Path(index_path).parent.mkdir(parents=True, exist_ok=True)
    
    dimension = embeddings.shape[1]
    
    # Use IndexFlatIP for cosine similarity (since embeddings are normalized)
    index = faiss.IndexFlatIP(dimension)
    index.add(embeddings.astype('float32'))
    
    # Save index
    faiss.write_index(index, f"{index_path}.bin")
    
    # Save metadata separately
    metadata = [chunk["metadata"] for chunk in chunks]
    texts = [chunk["text"] for chunk in chunks]
    with open(f"{index_path}_metadata.json", 'w') as f:
        json.dump({"texts": texts, "metadata": metadata}, f, indent=2)
    
    print(f"✅ FAISS index built with {index.ntotal} vectors (dimension={dimension})")
    print(f"   Saved to: {index_path}.bin")
    return index


# ── 2F: Quick Verification ────────────────────────────────
def verify_store(collection, model: SentenceTransformer):
    """Test the vector store with a sample query."""
    test_query = "What pigments are available for plastic applications?"
    query_embedding = model.encode([test_query], normalize_embeddings=True)
    
    results = collection.query(
        query_embeddings=query_embedding.tolist(),
        n_results=3
    )
    
    print(f"\n🔍 Test Query: '{test_query}'")
    print(f"   Top 3 results:")
    for i, (doc, meta) in enumerate(zip(results['documents'][0], results['metadatas'][0])):
        print(f"   [{i+1}] Page {meta['page_number']} | {meta['section_title']}")
        print(f"       {doc[:150]}...\n")


# ── Main ──────────────────────────────────────────────────
def run_embedding(chunks: Optional[List[Dict]] = None):
    """Complete embedding pipeline."""
    print("\n" + "="*60)
    print("STEP 2: Embedding & Vector Store")
    print("="*60)
    
    # Load chunks if not provided
    if chunks is None:
        chunks = load_chunks()
    
    # Load model
    model = load_embedding_model()
    
    # Generate embeddings
    embeddings = generate_embeddings(chunks, model)
    
    # Build ChromaDB store (primary)
    client, collection = build_chroma_store(chunks, embeddings)
    
    # Optionally also build FAISS index (uncomment if needed)
    # build_faiss_store(chunks, embeddings)
    
    # Verify
    verify_store(collection, model)
    
    return client, collection, model


if __name__ == "__main__":
    client, collection, model = run_embedding()
    print(f"\n🎉 Vector store ready! Documents indexed: {collection.count()}")
